### ISSUE TITLE
Show torrent fields: creation_date, created_by, encoding

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index-api-lib#38]
Relates to:
- https://github.com/torrust/torrust-index-gui/issues/278

**Comment by josecelano** [comment]
Hi @mario-nt I think this issue should be in the Index repo and it's already done, right?

**Comment by mario-nt** [comment]
@josecelano This issue should be in the index and types lib only (it is already completed and merged on those repos), I opened it back then here thinking I had to do some changes to this project, but changing the torrent response fields in the types lib was enough.
